services:
  frontend:
    build: ./ipcheckerfrontend-main
    ports:
      - "5000:80"
    develop:
      watch:
        - action: sync+restart
          path: ./ipcheckerfrontend-main/src
          target: /var/www/html/
    volumes:
      - ./utility:/var/utility:ro

  empty-total-ips:
    build: ./ipcheckertotalemptyips-main
    ports:
      - "9000-9002:80"
    deploy:
      replicas: 3
    develop:
      watch:
        - action: sync+restart
          path: ./ipcheckertotalemptyips-main/src
          target: /var/www/html/

  total-ips:
    build: ./ipcheckertotalips-main
    ports:
      - "7000-7002:80"
    deploy:
      replicas: 3
    develop:
      watch:
        - action: sync+restart
          path: ./ipcheckertotalips-main/src
          target: /var/www/html/

  ipv4-private-check:
    build: ./ipv4privatedetector-main
    ports:
      - "8000-8002:80"
    deploy:
      replicas: 3
    develop:
      watch:
        - action: sync+restart
          path: ./ipv4privatedetector-main/src
          target: /var/www/html/
    volumes:
      - ./utility:/var/utility:ro

  ipv6-extractor:
    build: ./ipv6extractor-main
    ports:
      - "6500-6502:80"
    deploy:
      replicas: 3
    develop:
      watch:
        - action: sync+restart
          path: ./ipv6extractor-main/src
          target: /var/www/html/
    volumes:
      - ./utility:/var/utility:ro

  ip-service-monitor:
    build: ./ipchecker-monitor
    ports:
      - "5500:80"
    develop:
      watch:
        - action: sync+restart
          path: ./ipchecker-monitor/src
          target: /var/www/html/
    volumes:
      - ./utility:/var/utility:ro